stages:
  - build
  - test
  - deploy

default:
  image: php:7

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: devops
  MYSQL_ROOT_PASSWORD: mysqlpwd
  ANSIBLE_HOST_KEY_CHECKING: "false"

before_script:
  - apt-get update -qq
  - apt-get install -yqq sshpass ansible python-pip python3-pip
  - pip install setuptools
  - cp .env.example .env
  - cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
  - docker-php-ext-install pdo_mysql
  - pear config-set php_ini /usr/local/etc/php/php.ini
  - pecl install xdebug
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar update -qn --no-ansi --prefer-dist
  - echo "192.168.1.10 server1" >> /etc/hosts
  - echo "192.168.1.28 server2" >> /etc/hosts
  - echo "192.168.1.34 db1" >> /etc/hosts
  - echo "192.168.1.22 db2" >> /etc/hosts

cache:
  paths:
    - vendor/

build:
  stage: build
  script:
    - php artisan config:cache
    - php artisan migrate
  artifacts:
    paths:
      - .env
      - vendor/

test:
  stage: test
  script:
    - php vendor/bin/phpunit

deploy:
  stage: deploy
  script:
    - ansible-playbook playbook.yml --user root -i inventory.ini --extra-vars ansible_password=root
  when: manual

