---

- name: Update system
  apt:    
    update_cache: yes

- name: Install Python3
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - python-pip
      - python-setuptools

- name: Install MySQL Server
  apt:
    name: default-mysql-server

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install PyMySQL
  pip:
    name: pymysql
    executable: pip3.7

- name: Create DB
  mysql_db:
    name: devops

- name:
  mysql_user:
    login_host: root
    login_password: ''
    name: root
    password: mysqlpwd
